sudo: required
language: scala
scala:
- 2.11.6
services:
- docker
env:
  global:
  - TERM=dumb
notifications:
  email: false
install: true
before_install:
- openssl aes-256-cbc -K $encrypted_11bcfc3b476d_key -iv $encrypted_11bcfc3b476d_iv
  -in vcap_services.json.enc -out vcap_services.json -d
- git clone https://github.com/openwhisk/openwhisk.git
- cd openwhisk
- ./tools/travis/setup.sh
script:
- ../tools/travis/build.sh
