sudo: required
language: scala - 2.11.6
services:
- docker
install: true
before_install:
- openssl aes-256-cbc -K $encrypted_7a7b287bd972_key -iv $encrypted_7a7b287bd972_iv -in vcap_services.json.enc -out vcap_services.json -d
- git clone https://github.com/openwhisk/openwhisk.git
- cp ./tests/* ./openwhisk/tests/src/packages/
- "./openwhisk/tools/travis/setup.sh"

script:
- VCAP_SERVICES_FILE="$(readlink -f vcap_services.json)"
- OPENWHISK_HOME=$(cd openwhisk && pwd)
- "$OPENWHISK_HOME/tools/build/scanCode.py $OPENWHISK_HOME"
- cd $OPENWHISK_HOME/ansible
- ANSIBLE_CMD="ansible-playbook -i environments/travis"
- "$ANSIBLE_CMD setup.yml"
- "$ANSIBLE_CMD prereq.yml"
- "$ANSIBLE_CMD couchdb.yml"
- "$ANSIBLE_CMD initdb.yml"
- cd $OPENWHISK_HOME
- "./gradlew distDocker"
- cd $OPENWHISK_HOME/ansible
- "$ANSIBLE_CMD openwhisk.yml"
- cd $OPENWHISK_HOME
- WHISKPROPS_FILE="$OPENWHISK_HOME/whisk.properties"
- sed -i 's:^[ \t]*vcap.services.file[ \t]*=\([ \t]*.*\)$:vcap.services.file='$VCAP_SERVICES_FILE':'  $WHISKPROPS_FILE
- WSK_CLI=$OPENWHISK_HOME/bin/wsk
- AUTH_KEY=$(cat $OPENWHISK_HOME/config/keys/auth.whisk.system)
- EDGE_HOST=$(grep '^edge.host=' $WHISKPROPS_FILE | cut -d'=' -f2)
- source $OPENWHISK_HOME/../install.sh $EDGE_HOST $AUTH_KEY $WSK_CLI - cp .$OPENWHISK_HOME/../tests/* ./openwhisk/tests/src/packages/
- X="./gradlew :tests:test "
- for f in $(ls $OPENWHISK_HOME/../tests | sed -e 's/\..*$//'); do X="$X --tests \"packages.$f\""; done
- eval $X
